language: python

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.4
          env: TOXENV=py34

install:
  - pip install tox --use-mirrors

script:
  - tox
