language: python

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py27
        - os: linux
          python: 3.4
          env: TOXENV=py34
        # Use generic language for OS X
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py34

# Perform the manual Python installation steps on OS X
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOXENV" == "py27" ]]; then brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOXENV" == "py34" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOXENV" == "py27" ]]; then virtualenv venv -p python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOXENV" == "py34" ]]; then virtualenv venv -p python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install:
  - pip install tox --use-mirrors

script:
  - tox

env:
  - TOXENV=py27
  - TOXENV=py34
